SELECT @@VERSION
SELECT @@ROWCOUNT
SELECT @@SPID, @@MAX_CONNECTIONS

SELECT @@VERSION;	
SELECT @@SERVERNAME;	
SELECT @@SPID;	
SELECT @@ROWCOUNT;
SELECT @@ERROR;	
SELECT @@IDENTITY;	
SELECT @@TRANCOUNT;	
SELECT @@CONNECTIONS;	
SELECT @@CPU_BUSY;
SELECT @@TOTAL_READ;
SELECT @@TOTAL_WRITE;
SELECT @@LOCK_TIMEOUT;
SELECT @@LANGUAGE;	
SELECT @@DATEFIRST;	
SELECT @@MAX_CONNECTIONS;

